pipeline {
    agent any

    environment {
        IMAGE_NAME = 'svr-image-1993190p'
        CONTAINER_NAME = 'server1-1993190p'
    }

    triggers {
        pollSCM('H/4 * * * *') // every 4 minutes
    }

    stages {

        stage('ST1-1993190p') {
            steps {
                echo 'ST1-1993190p: Setup Release Environment Completed.'
            }
        }

        stage('ST2-1993190p') {
            steps {
                script {
                    // Remove old container if exists
                    sh "docker rm -f ${CONTAINER_NAME} || true"
                    // Run new container
                    sh "docker run -dit --name ${CONTAINER_NAME} -p 32700:80 ${IMAGE_NAME}"
                }
                echo 'ST2-1993190p: Server1 is successfully created'
            }
        }

        stage('ST3-1993190p') {
            steps {
                echo 'ST3-1993190p: Server1 is healthy – Health check done'
            }
        }

        stage('ST4-Parallel-1993190p') {
            parallel {
                stage('ST4-1993190p') {
                    steps {
                        echo 'ST4-Parallel-1993190p: Security Scrutinises'
                    }
                }
                stage('ST4A-1993190p') {
                    steps {
                        echo 'ST4A-1993190p: SQLI Check Completed'
                    }
                }
                stage('ST4B-1993190p') {
                    steps {
                        echo 'ST4B-1993190p: XSS Check Completed'
                    }
                }
            }
        }

        stage('ST5-1993190p') {
            steps {
                script {
                    def userInput = input message: 'Continue the pipeline?', ok: 'Proceed', parameters: [
                        choice(name: 'Decision', choices: ['Proceed', 'Abort'], description: 'Select Proceed or Abort')
                    ]

                    if (userInput == 'Abort') {
                        error("ST5-1993190p: Pipeline aborted by user.")
                    } else {
                        echo 'ST5-1993190p : Continue the pipeline.'
                    }
                }
            }
        }

        stage('ST6-1993190p') {
            steps {
                echo 'ST6-1993190p : Ready for next phase'
            }
        }
    }
}
